[build]
    command = "npm run build"
    publish = "out"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-sitemap"
# https://github.com/netlify-labs/netlify-plugin-sitemap
    [plugins.inputs]
    prettyURLs = true
    trailingSlash = false
    exclude = [
        '**/404*',
    ]

# Disabled because it took forever and never finished
# [[plugins]]
# # https://www.npmjs.com/package/netlify-plugin-checklinks
# package = "netlify-plugin-checklinks"

#     [plugins.inputs]
#     # Recurse through all the links and asset references on your page, starting
#     # at the entrypoints
#     recursive = true

#     # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
#     # by default. Enabling pretty mode makes the output easier on the eyes.
#     pretty = true

#     # Report on all broken links to external pages.
#     # Enabling this will make your tests more brittle, since you can't control
#     # external pages.
#     checkExternal = true

[[plugins]]
# https://github.com/Tom-Bonnike/netlify-plugin-inline-source#readme
package = "netlify-plugin-inline-source"

    # All inputs are optional, so you can omit this section.
    # Defaults are shown below.
    # You can also refer to the `inline-source` documentation: https://github.com/popeindustries/inline-source#usage.
    [plugins.inputs]
    # Attribute used to parse sources. All tags will be parsed if set to `false`.
    attribute = "inline"

    # Enable/disable compression of inlined content.
    compress = true

    # Maintain leading whitespace when `compress` is `false`.
    pretty = false

    # Disable inlining based on tag, type, and/or format.
    ignore = []

    # Convert `<img inline src="*.svg" />` to `<img>` and not `<svg>`.
    svgAsImage = false


[[plugins]]
# https://github.com/jonahsnider/netlify-cache-nextjs#readme
package = "netlify-plugin-cache-nextjs"

# [[plugins]]
# # https://github.com/philhawksworth/netlify-plugin-minify-html#readme
# package = "netlify-plugin-minify-html"

#     # Specify which deploy contexts we'll minify HTML in.
#     # Supports any Deploy Contexts available in Netlify.
#     # https://docs.netlify.com/site-deploys/overview/#deploy-contexts
#     [plugins.inputs]
#     contexts = [
#         'production',
#         'branch-deploy',
#         'deploy-preview'
#     ]

#     # Optionally, override the default options for the minification
#     # https://github.com/kangax/html-minifier#options-quick-reference
#     [plugins.inputs.minifierOptions]
#     removeComments = true
#     collapseInlineTagWhitespace = true
#     collapseWhitespace = true
#     minifyCSS = true
#     minifyJS = true
#     sortAttributes = true
#     sortClassName = true